### ISSUE TITLE
SqlTransactionのExecuteメソッドの改善

### ISSUE THREAD

**Issue by kecbigmt** [maru44/animar#6]
こんにちは、こちらの記事を拝見した者です。
https://zenn.dev/maru44/articles/b9e07e91a0ea77

参考にsqlhandlerの実装も見ていたのですが、SqlTransactionのExecuteメソッドについて、2つ気になったところがあったので念のためコメントを残しておきます。

https://github.com/maru44/animar/blob/55ba485dea466613cfa21717c943f5486b2a85ea/internal/pkg/infrastructure/sqlhandler.go#L99-L112

### 1. deferの位置
```go
stmt, err := t.Tx.Prepare(statement)
defer stmt.Close()
if err != nil {
  return res, err
}
```

という順番だと、Prepareがエラーだった際にstmtがnilのままCloseメソッドが呼び出されてしまうため、
```
invalid memory address or nil pointer dereference
```
のpanicが発生してしまいます。

deferをエラーハンドリングよりもあとに持っていくと必要があると思います

### 2. エラーの際にreturnされない

```go
exe, err := stmt.Exec(args...)
if err != nil {
  log.Print(err)
}
res.Result = exe
return res, nil
```

Execのエラーハンドリングでログの出力をしているだけでreturnしていないので、エラーなのにそのまま処理が進んでしまいます。

ifの中の最後で`return res, err`のようにする必要があるように見えます。

以上です。
記事やソースコード、大変参考になりました。

**Comment by maru44** [comment]
あ、ほんとですね

ありがとうございます！

**Comment by maru44** [comment]
ちょっと立て込んでて直すの遅くなってしまったのですが修正しました
ありがとうございます
